# Generated by Django 2.2.14 on 2022-11-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20221105_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=20, unique=True, verbose_name='手机号'),
        ),
    ]
