# Generated by Django 3.2.16 on 2022-11-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20221109_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'managed': False, 'verbose_name': '学科', 'verbose_name_plural': '学科'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '老师', 'verbose_name_plural': '老师'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
